name: pas
channels:
  - conda-forge
  - bioconda
  - ccordoba12
  - ruby-lang
  - r
  - trent
dependencies:
  - snakemake=5.3.0
  - pandoc=2.3.1=0
  - ruby=2.2.3=0
  - r-leaflet=2.0.2
  - r-dplyr=0.7.6
  - r-stringr=1.3.1
  - r-lubridate=1.7.4
  - r-rmarkdown=1.10
  - r-devtools=1.13.6
  - r-webshot=0.5.1
  - rpy2=2.9.4
  - gdal=2.2.4
  - r-rgdal=1.3_6
  - phantomjs=2.1.1
